backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/AjaxController.php
<?php
/**
 * Created by PhpStorm.
 * User: dusty
 * Date: 04.08.16
 * Time: 1:05
 */

namespace frontend\controllers;

use common\models\Feed;
use Yii;
use yii\web\Controller;
use common\models\FeedInterface;


/**
 * Ajax controller
 */
class AjaxController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Получение записей для страницы в json формате (+ постраничность)
     */
    public function actionFeed()
    {
        $filter = Yii::$app->request->post("filter",NULL);
        $date_filter = Yii::$app->request->post("date",false);
        $page = Yii::$app->request->post("page",NULL);

        if ($filter !== NULL)
        {
            $feed = Feed::getFeedPage($page, $filter,$date_filter);
            $pages = Feed::getPageNum($filter,$date_filter);
        }
        else
        {
            $feed = Feed::getFeedPage($page,[],$date_filter);
            $pages = Feed::getPageNum([],$date_filter);
        }

        /* @var $feed FeedInterface[] */
        if (count($feed))
        {
            $result = [];
            foreach ($feed as $entity)
            {
                $row = [];
                $row['title'] = $entity->feed_title();
                $row['content'] = $entity->feed_content();
                $row['picture'] = $entity->feed_picture();
                $row['date'] = $entity->feed_date();

                $result[] = $row;
            }

            $feed_json = json_encode($result);

            return <<<JSON
{"status": "success", "feed": {$feed_json}, "pages": {$pages}}
JSON;

        }
        else
        {
            return <<<JSON
{"status": "error", "msg": "Нет записей"}
JSON;

        }

    }

    /**
     * Выдача статистики
     */
    public function actionStat()
    {
        $films_all_time_stat = Feed::getRecordsCount(["Film"]);
        $music_all_time_stat = Feed::getRecordsCount(["Music"]);
        $events_all_time_stat = Feed::getRecordsCount(["Event"]);

        $all_time_stat = Feed::getRecordsCount();

        $today = date("Y-m-d");

        $films_today_stat = Feed::getRecordsCount(["Film"],$today);
        $music_today_stat = Feed::getRecordsCount(["Music"],$today);
        $events_today_stat = Feed::getRecordsCount(["Event"],$today);

        $today_stat = Feed::getRecordsCount([],$today);


        return <<<JSON
{"status": "success", "stat":[
    {"title": "Сегодня фильмов", "content": "{$films_today_stat}"},
    {"title": "Сегодня музыки", "content": "{$music_today_stat}"},
    {"title": "Сегодня событий", "content": "{$events_today_stat}"},
    {"title": "Сегодня записей", "content": "{$today_stat}"},
    {"title": "Всего фильмов", "content": "{$films_all_time_stat}"},
    {"title": "Всего музыки", "content": "{$music_all_time_stat}"},
    {"title": "Всего событий", "content": "{$events_all_time_stat}"},
    {"title": "Всего записей", "content": "{$all_time_stat}"}
]}
JSON;


    }


}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;



/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

}

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use app\assets\DatePickerAsset;

$this->title = 'Тестовое задание';

$this->registerJs(
    <<<JS
    //запрос и обновление ленты
    var page = 1;

    function requestFeed()
    {
        $.ajax(
            {
                url: "/ajax/feed",
                type: "POST",
                data: {page: page, filter: getFilter(), date: $("#date-filter").val()},
                dataType: "json"
            }
        ).done(
            // обработка сообщения-ответа сервера
            function (msg)
            {
                $("#feed").empty();
                $("#pagination").empty();
                if (msg.status === 'success')
                {
                    $.each(msg.feed, function(i,item){
                        $("#feed")
                        .append(
                            $("<div/>",{class: "row"}).append(
                                $("<div/>", {class: "col-md-4"}).append(
                                    $("<img/>",{src: item.picture, class: "img-responsive"})
                                )

                            ).append(
                                $("<div/>", {class: "col-md-8"}).append(

                                    $("<h3/>",{text: item.title})
                                )
                                .append(
                                    $("<p/>").html(item.content)
                                )

                            )

                        )
                    });

                    var paginator = $("<ul/>",{class: "pagination"});

                    for(var i = 1; i <= msg.pages; i++)
                    {
                        var page_link = $("<a/>",{href: "#", "data-page": i});

                        if (i === page)
                        {
                            page_link.append(
                                $("<strong/>", {text: i})
                            );
                        }
                        else
                        {
                            page_link.text(i);
                        }

                        page_link.click(
                            function(e)
                            {
                                e.preventDefault();
                                page = $(this).data("page");
                                requestFeed();
                            }
                        );

                        paginator.append(
                            $("<li/>").append(page_link)
                        );

                    }

                    $("#pagination").append(
                        $("<div/>",{class: "col-sm-12"})
                    ).append(paginator);
                }
                else
                {
                    $("#feed").append(

                        $("<div/>", {class: "alert alert-danger", role: "alert", text: msg.msg})
                    );

                }

            }
        )
        .fail(
            // вывод ошибки
            function()
            {
                $("#feed").empty();
                $("#feed").append(

                    $("<div/>", {class: "alert alert-danger", role: "alert", text: "Ошибка получения данных"})
                );

            }
        );
    }

    // получение фильтра
    function getFilter()
    {
        var result = [];
        $("#filter input:checked").each(
            function()
            {
                result[result.length] = $(this).data('filter'); // получаем фильтр из дата-атрибута
            }
        );

        return result;
    }


    // одинаковые обработчики смены фильтра
    $("#filter [data-filter]").change(
        function()
        {
            page = 1;
            requestFeed();
        }
    );

    $("#date-filter").change(
        function()
        {
            page = 1;
            requestFeed();
        }
    );

    // обработка клика по статистике
    $("a[href='/site/stat']").click(
        function(event)
        {
            event.preventDefault();

            $("#statModal .modal-body").empty();

            $.ajax(
                {
                    url: "/ajax/stat",
                    type: "POST",
                    data: {},
                    dataType: "json"
                }
            ).done(
                // обработка сообщения-ответа сервера
                function (msg)
                {
                    if (msg.status === 'success')
                    {
                        // собираем таблицу данных статистики
                        var table = $("<table/>",{class:"table"});
                        $.each(msg.stat, function(i, item){
                            table.append( // данные - это массив из пар title + content
                                $("<tr/>").append(
                                    $("<td/>",{text:item.title})
                                ).append(
                                    $("<td/>",{text:item.content})
                                )
                            )
                        });
                        $("#statModal .modal-body").append(
                            table
                        );
                    }
                    else
                    {
                        $("#statModal .modal-body").append(
                            $("<div/>", {class: "alert alert-danger", role: "alert", text: msg.msg})
                        );

                    }
                }
            ).fail(
                function ()
                {
                    $("#statModal .modal-body").append(
                        $("<div/>", {class: "alert alert-danger", role: "alert", text: "Ошибка получения данных"})
                    );
                }
            ).always(
                function()
                {
                    $("#statModal").modal();
                }
            );


        }
    );

    $("#date-filter").datepicker({clearBtn: true,language:'ru', endDate:"now"});

    //requestFeed();
JS
);

DatePickerAsset::register($this);
?>
<div class="site-index">


    <div class="body-content">

        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-12 col-lg-offset-3 col-md-offset-2">
                <h2>Лента</h2>
                <div id="filter" class="row">
                    <div class="col-sm-12 form-group">
                        <label for="film">Фильмы</label><input id="film" type="checkbox" data-filter="Film"/>
                        <label for="music">Музыка</label><input id="music" type="checkbox" data-filter="Music"/>
                        <label for="event">События</label><input id="event" type="checkbox" data-filter="Event"/>
                        <div class="form-inline pull-right">
                            <input id="date-filter" class="form-control"/>
                        </div>
                    </div>
                </div>

                <div id="feed" class="row">

                </div>
                <div id="pagination" class="row">

                </div>

            </div>

        </div>

    </div>
</div>

<!-- Modal -->
<div id="statModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Статистика</h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>

    </div>
</div>